spring:
  application:
    name: gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true
        routes:
          - id: customer
            uri: lb://customer
            predicates:
              - Path=/api/v1/customers/**


server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true