server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    password: sahil1303
    url: jdbc:mysql://localhost:3306/fraud
    username: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      show-sql: true
